# Generated by Django 3.1.5 on 2021-03-10 16:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(default='', max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=25)),
                ('customerName', models.CharField(max_length=100)),
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('aadhaarId', models.CharField(max_length=12, unique=True)),
                ('nomineeName', models.CharField(max_length=100)),
                ('income', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(10)])),
                ('dob', models.DateField(default=datetime.date(2021, 3, 10))),
            ],
        ),
    ]
