# Generated by Django 3.1.5 on 2021-03-10 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyforloan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
