# Generated by Django 3.1.5 on 2021-03-10 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyforloan', '0002_auto_20210310_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='applicationDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='customer',
            name='aadhaarId',
            field=models.DecimalField(decimal_places=0, max_digits=12, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
