# Generated by Django 3.1.5 on 2021-03-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applyforloan', '0003_auto_20210310_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldAsset',
            fields=[
                ('assetID', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goldtype', models.CharField(choices=[('B', 'Biscuit'), ('O', 'Ornament'), ('C', 'Coin')], max_length=1)),
                ('customerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applyforloan.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('loanId', models.AutoField(primary_key=True, serialize=False)),
                ('principalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('lentRateOfInterest', models.DecimalField(decimal_places=2, default=9.5, max_digits=5)),
                ('lentGoldValue', models.DecimalField(decimal_places=2, default=50000, max_digits=8)),
                ('lentLoanTenure', models.PositiveSmallIntegerField()),
                ('loanApplicationStatus', models.CharField(choices=[('APP', 'Approved'), ('REJ', 'Rejected'), ('FUP', 'Under process')], default='FUP', max_length=3)),
                ('ltvRatio', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('assetId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applyforloan.goldasset')),
                ('customerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applyforloan.customer')),
            ],
        ),
    ]
