# Generated by Django 3.1.5 on 2021-03-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyforloan', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='emi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
