# Generated by Django 3.1.5 on 2021-03-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyforloan', '0006_loanapplication_emi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='emi',
            field=models.PositiveIntegerField(),
        ),
    ]
