# Generated by Django 3.1.5 on 2021-03-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyforloan', '0007_auto_20210314_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='emi',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
