# Generated by Django 3.1.5 on 2021-03-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyforloan', '0008_auto_20210315_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='totalLoanAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='principalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
