# Generated by Django 3.1.5 on 2021-03-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyforloan', '0009_auto_20210315_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='emipaid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
