# Generated by Django 3.1.5 on 2021-03-27 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyforloan', '0010_loanapplication_emipaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoldValue', models.DecimalField(decimal_places=2, default=50000, max_digits=8)),
                ('RateOfInterest', models.DecimalField(decimal_places=2, default=9.5, max_digits=5)),
                ('ltvRatio', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='ltvRatio',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='lentltvRatio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='lentGoldValue',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='lentRateOfInterest',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
