# Generated by Django 3.1.5 on 2021-02-02 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerName', models.CharField(max_length=100)),
                ('customerId', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('aadhharId', models.CharField(max_length=12, unique=True)),
                ('nomineeName', models.CharField(max_length=100)),
                ('income', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='GoldAsset',
            fields=[
                ('assetID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goldType', models.CharField(choices=[('B', 'Biscuit'), ('O', 'Ornament'), ('C', 'Coin')], max_length=1)),
                ('purity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currentGoldValue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condition', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestUserName', models.CharField(max_length=100)),
                ('emailAddress', models.CharField(max_length=50)),
                ('contactNumber', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('uniqueLoanId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lentRateOfInterest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lentGoldValue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lentLoanTenure', models.PositiveSmallIntegerField()),
                ('loanApplicationStatus', models.CharField(choices=[('APP', 'Approved'), ('REJ', 'Rejected'), ('FUP', 'Under process')], max_length=3)),
                ('ltvRatio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
